server:
    port: 8080

#mybatis:
#mappers-locations: classpath:/mybatis/mappers/*.xml
#config-location: classpath:/mybatis/mybatis-config.xml

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jeccurriculum?serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      prefix: classpath*:/templates/

mybatis:
    mapper-locations: classpath:mappers/*Mapper.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


